spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/artistica?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: "root"
  servlet:
    multipart:
      max-file-size: 99MB
      max-request-size: 99MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  mvc:
    hiddenmethod:
      filter:
        enabled: true


app:
  default:
    admin:
      password: topsecret

  #Cloudinary Properties
cloudinary:
  api-key: 763571878292865
  api-secret:  ${CLOUDINARY_API_SECRET}
  cloud-name: dmumqnbm0

mail:
  default-encoding: UTF-8
  host: smtp.gmail.com
  username: artistica.study@gmail.com
  password: ${MAIL_API_SECRET}
  port: 587
  properties:
    mail:
      smtp:
        auth: true
        ssl.trust: smtp.gmail.com
  protocol: smtp
  test-connection: false

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE